using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CoreBuilder.Models;
public class PageContent { [Key] public Guid Id { get; set; } = Guid.NewGuid(); public Guid PageId { get; set; } [ForeignKey("PageId")] public Page? Page { get; set; } public ContentType ContentType { get; set; } [Required] public required string Title { get; set; } public string? Description { get; set; } public string? MediaUrl { get; set; } public string? ThumbnailUrl { get; set; } public string? EmbedCode { get; set; } public string? LinkUrl { get; set; } public string? LinkText { get; set; } public int DisplayOrder { get; set; } = 0; public bool IsActive { get; set; } = true; public string? MetaData { get; set; } public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public DateTime? UpdatedAt { get; set; } }
public enum ContentType { Image = 0, Video = 1, SliderItem = 2, TextBlock = 3, File = 4, TeacherProfile = 5, StaffProfile = 6, WidgetSlider = 10, WidgetAnnouncements = 11, WidgetNews = 12 }
public static class ContentTypeExtensions { public static string GetDisplayName(this ContentType type) { return type switch { ContentType.Image => "Fotograf", ContentType.Video => "Video", ContentType.SliderItem => "Slider", ContentType.TextBlock => "Metin", ContentType.File => "Dosya", ContentType.TeacherProfile => "Ögretmen", ContentType.StaffProfile => "Personel", ContentType.WidgetSlider => "Slider Modülü", ContentType.WidgetAnnouncements => "Duyurular Modülü", ContentType.WidgetNews => "Haberler Modülü", _ => "Içerik" }; } public static string GetIcon(this ContentType type) { return type switch { ContentType.Image => "oi-image", ContentType.Video => "oi-video", ContentType.SliderItem => "oi-layers", ContentType.TextBlock => "oi-text", ContentType.File => "oi-file", ContentType.TeacherProfile => "oi-people", ContentType.StaffProfile => "oi-briefcase", ContentType.WidgetSlider => "oi-play-circle", ContentType.WidgetAnnouncements => "oi-bullhorn", ContentType.WidgetNews => "oi-rss", _ => "oi-document" }; } }

