'------------------------------------------------------------------------------
' <auto-generated>
'     Bu kod araç tarafından oluşturuldu.
'
'     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
'     kod yeniden oluşturuldu.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Site_Mobile

    '''<summary>
    '''Head1 denetimi.
    '''</summary>
    '''<remarks>
    '''Otomatik olarak oluşturulan alan.
    '''Tasarımcı dosyasından arka plan kod dosyasına alan taşıma bildiriminde değişiklik yapmak için.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''HeadContent denetimi.
    '''</summary>
    '''<remarks>
    '''Otomatik olarak oluşturulan alan.
    '''Tasarımcı dosyasından arka plan kod dosyasına alan taşıma bildiriminde değişiklik yapmak için.
    '''</remarks>
    Protected WithEvents HeadContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''form1 denetimi.
    '''</summary>
    '''<remarks>
    '''Otomatik olarak oluşturulan alan.
    '''Tasarımcı dosyasından arka plan kod dosyasına alan taşıma bildiriminde değişiklik yapmak için.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''FeaturedContent denetimi.
    '''</summary>
    '''<remarks>
    '''Otomatik olarak oluşturulan alan.
    '''Tasarımcı dosyasından arka plan kod dosyasına alan taşıma bildiriminde değişiklik yapmak için.
    '''</remarks>
    Protected WithEvents FeaturedContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''MainContent denetimi.
    '''</summary>
    '''<remarks>
    '''Otomatik olarak oluşturulan alan.
    '''Tasarımcı dosyasından arka plan kod dosyasına alan taşıma bildiriminde değişiklik yapmak için.
    '''</remarks>
    Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''ViewSwitcher1 denetimi.
    '''</summary>
    '''<remarks>
    '''Otomatik olarak oluşturulan alan.
    '''Tasarımcı dosyasından arka plan kod dosyasına alan taşıma bildiriminde değişiklik yapmak için.
    '''</remarks>
    Protected WithEvents ViewSwitcher1 As Global.System.Web.UI.UserControl
End Class
